# Based on Lianmin's dockerfile https://hub.docker.com/repository/docker/lmzheng/ml-gpu

FROM  nvidia/cuda:10.0-cudnn7-devel
RUN apt-get update --fix-missing


ARG BUILD_EXTR_PAR

########## C++ and Java Core ##########
RUN apt-get install -y --no-install-recommends \
        git make libgtest-dev cmake wget unzip libtinfo-dev libz-dev \
        libcurl4-openssl-dev libopenblas-dev g++ sudo \
        pkg-config zip zlib1g-dev unzip python openjdk-8-jdk curl
RUN cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib
# bazel
RUN cd /tmp && wget https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel-0.21.0-installer-linux-x86_64.sh && chmod u+x bazel-0.21.0-installer-linux-x86_64.sh && ./bazel-0.21.0-installer-linux-x86_64.sh


########## Developer Core ########## 
RUN apt-get install -y vim openssh-server sshfs tmux htop psmisc


########## Python ##########
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update
RUN apt-get install -y python3.7 python3.7-dev
RUN rm -f /usr/bin/python3 && ln -s /usr/bin/python3.7 /usr/bin/python3
RUN cd /tmp && wget -q https://bootstrap.pypa.io/get-pip.py && python3.7 get-pip.py
# python packages
RUN pip3 install nose pylint==1.9.4 six numpy nose-timer cython decorator scipy tornado typed_ast pytest \
        mypy orderedset runtime attrs requests Pillow packaging psutil matplotlib tqdm xgboost \
        antlr4-python3-runtime 


########## Other Libraries ##########
# llvm
RUN echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main\
      >> /etc/apt/sources.list.d/llvm.list
RUN echo deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial main\
      >> /etc/apt/sources.list.d/llvm.list
RUN wget -q -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
RUN apt-get update && apt-get install -y llvm-9 llvm-8 llvm-7 clang-9 clang-8 clang-7


########## Environment Variables  ##########
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/root/.local/bin/:${PATH}
ENV CPLUS_INCLUDE_PATH=/usr/local/cuda/include:${CPLUS_INCLUDE_PATH}
ENV C_INCLUDE_PATH=/usr/local/cuda/include:${C_INCLUDE_PATH}
ENV LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/nvidia/lib64:${LIBRARY_PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/nvidia/lib64:/root/.local/lib:${LD_LIBRARY_PATH}
ENV TMP=/tmp
ENV TF_CPP_MIN_LOG_LEVEL=2


########## Host User Setup  ##########
# These let you set the default user to match the host user to make sharing files easier
ARG USER=docker
ARG UID=1000
ARG GID=1000

RUN useradd -m ${USER} --uid=${UID}
RUN adduser ${USER} sudo
WORKDIR /home/${USER}
USER ${UID}
